### ISSUE TITLE
R551 sensor does not get right image imgae_to_pc

### ISSUE THREAD

**Issue by baku-hatsu** [brianrho/FPM#11] opened 2018-12-16 12:59 UTC
python output:
----------Extract Fingerprint Image------------

Options:
        Press 1 to enter serial port settings
        Press 2 to scan a fingerprint and save the image
        Press 3 to view help
        Press 4 to exit

>> 1

Enter Arduino serial port number: COM3
Enter serial port baud rate: 57600

Options:
        Press 1 to enter serial port settings
        Press 2 to scan a fingerprint and save the image
        Press 3 to view help
        Press 4 to exit

>> 2

Enter filename/path of output file (without extension): asd
SEND IMAGE TO PC test

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 1
0
[+]Read complete

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 17
0 0 0 0 0 1 F4 0 3 FF FF FF FF 0 2 0 6
[+]Read complete

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 17
0 0 0 0 0 1 F4 0 3 FF FF FF FF 0 2 0 6
[+]Read complete
Found fingerprint sensor!
Capacity: 500
Packet length: 128

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 1
0
[+]Read complete

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 17
0 0 0 0 0 1 F4 0 3 FF FF FF FF 0 2 0 6
[+]Read complete
Packet length set to 128 bytes
Waiting for a finger...

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 1
2
[+]Read complete

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 1
0
[+]Read complete
Image taken

[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x7
[+]Length: 1
0
[+]Read complete
Starting image stream...
Image saved as asd.bmp
FF FF FF FF FF FF FF FF FF FF FF FF FF EF 1 FF FF FF FF 2  0 82 FF FF FF FF

Picture is this:

![asd](https://user-images.githubusercontent.com/37425895/50053729-b228d300-0142-11e9-9d45-d526d65bc892.png)

Arduino seriam monitor shows this:
[+]Got header
[+]Address: 0xFFFFFFFF
[+]PID: 0x2
[+]Length: 128
⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮FF ⸮EF 1 ⸮FF ⸮FF ⸮FF ⸮FF 2 
Read data failed: -1

Error receiving packet 67

**Comment by brianrho** [comment] 2018-12-16 13:18
No, I said to provide a screenshot of the python console itself after the image is done being transferred. Dont paste the text. Upload an image of the console.

**Comment by baku-hatsu** [comment] 2018-12-16 13:32
When i turn off debuging the python exe doesnt work:
![image](https://user-images.githubusercontent.com/37425895/50054143-cd4a1180-0147-11e9-8c3f-5a3137e25653.png)


With debugging is open, i get this:
![image](https://user-images.githubusercontent.com/37425895/50054126-97a52880-0147-11e9-84b7-c6d6749ce47b.png)

**Comment by brianrho** [comment] 2018-12-16 13:40
Okay. So this is the latest version of the library, right? And in the first case, you get "Timeout!" after waiting for a few seconds?

**Comment by brianrho** [comment] 2018-12-16 13:41
The "Timeout!" doesn't show immediately the image stream begins?

**Comment by baku-hatsu** [comment] 2018-12-16 13:42
Yes it dosnt show immediately, it takes like 10 or little more seconds. And this is latest version of library, with R551 uncommented line

**Comment by brianrho** [comment] 2018-12-16 13:55
It seems your module has a different image size of 192x192. I've pushed a change to the python script. Assign True to FPM_R551_MODULE at the top and run it. Let me know how it works out

**Comment by brianrho** [comment] 2018-12-16 13:57
It's important that debugging is turned off for this sketch because the debug messages go through the same Serial port as the image stream, so all those debug strings end up getting written to the bmp file, which isnt what you want.

**Comment by baku-hatsu** [comment] 2018-12-16 14:10
I get same error:
![image](https://user-images.githubusercontent.com/37425895/50054667-fcaf4d00-014c-11e9-9b72-387227b63fae.png)
Did you recompiled python exe or it read from that file?

**Comment by brianrho** [comment] 2018-12-16 14:18
No I haven't rebuilt the exe. Can you run the python script?

**Comment by baku-hatsu** [comment] 2018-12-16 14:20
I edite phyton file, but i dont see changes, so i assume your changes is only on file, not on .exe, to build exe from python file i cant yet, i had lots of trouble with python on Windows 10, would be good if you could build it

**Comment by baku-hatsu** [comment] 2018-12-16 14:39
According to documentation image buffer size can be 192x192 with depth of 8
![image](https://user-images.githubusercontent.com/37425895/50054970-2ec2ae00-0151-11e9-85da-ca6bb0c29c41.png)

**Comment by brianrho** [comment] 2018-12-16 14:47
Yeah, made a mistake. In the python code, change the WIDTH = 96 to 192.

**Comment by baku-hatsu** [comment] 2018-12-16 14:50
I tried that myself, i still get error. Console looks like this:
![image](https://user-images.githubusercontent.com/37425895/50055085-a1805900-0152-11e9-94a5-cbecad28aa20.png)
Image looks like this:
![othertest](https://user-images.githubusercontent.com/37425895/50055094-acd38480-0152-11e9-8573-c78b3fe4b4a8.png)

**Comment by brianrho** [comment] 2018-12-16 14:55
That looks like the very last packet. Can you try running it again? I want to see if the failure is consistent

**Comment by brianrho** [comment] 2018-12-16 14:59
I think you didnt change this line `FPM_R551_MODULE = False` to `True` like I said. The arduino ends up waiting forever for another packet, when the image stream is already completed.

**Comment by baku-hatsu** [comment] 2018-12-16 15:01
Two tries out of five did not gave error message, however rest of the tries gave same error message. All scanned images was same size.
Code is:
![image](https://user-images.githubusercontent.com/37425895/50055193-1b651200-0154-11e9-8354-ab66c77d363c.png)

**Comment by brianrho** [comment] 2018-12-16 15:03
What is the exact size? Check the properties of the generated image and send a screenshot of that. Also a screenshot of the console output when there was no error.

**Comment by baku-hatsu** [comment] 2018-12-16 15:07
Scanned image size is 192x192 pixels 
Console look like this:
port is COM3 and bound is 57600
![image](https://user-images.githubusercontent.com/37425895/50055257-118fde80-0155-11e9-8dc4-c640ef3f265e.png)

**Comment by baku-hatsu** [comment] 2018-12-16 15:08
As well im using python -m pip install pyserial as for serial import for python, that maybe be other kind of serial?

**Comment by brianrho** [comment] 2018-12-16 15:13
No, its fine. Run the sketch, but use the serial monitor instead.

**Comment by brianrho** [comment] 2018-12-16 15:14
Looks like the problem isnt with the script, its with the module not sending FPM_ENDDATAPACKET to show that its done.

**Comment by brianrho** [comment] 2018-12-16 15:16
You haven't made any changes to the image_to_pc sketch, right?

**Comment by baku-hatsu** [comment] 2018-12-16 15:18
No, i havent, only to FPM.h library, where i uncommented one line of code 
/* R551 is different in a few ways (no high-speed search, off-by-one template indices)
   uncomment this line if you have one of those */
#define FPM_R551_MODULE

**Comment by brianrho** [comment] 2018-12-16 15:20
Okay. Comment out line 663 `outStream->write(byte);` in FPM.cpp. Enable debugging. Then run the sketch with the serial monitor alone. Let me see what is printed in the last few packets of the image, before the error shows up.

**Comment by brianrho** [comment] 2018-12-16 15:30
The FFs arent a problem, they just show that most of the image is white pixels as expected. 
Comment out these debug lines in the code: 
```
[+]Got header
[+]Address: 0xFFFFFFFF
```
As well as line 670: `FPM_DEBUG_HEX(byte); FPM_DEBUG_PRINT(" ");`

I want only the PID and length to be printed.

**Comment by baku-hatsu** [comment] 2018-12-16 15:35
`[+]PID: 0x2
[+]Length: 128
Read data failed: -1

Error receiving packet 144

`

**Comment by brianrho** [comment] 2018-12-16 15:36
Run it a few more times, check that it gives the same result and stops at the same packet

**Comment by baku-hatsu** [comment] 2018-12-16 15:38
Yes its always same packet

**Comment by brianrho** [comment] 2018-12-16 15:41
And this is the very last packet always:
```
[+]PID: 0x2
[+]Length: 128
```

Can you check if any packet has a PID of 0x8?

**Comment by baku-hatsu** [comment] 2018-12-16 15:42
There is no packet with PID 0x8

**Comment by brianrho** [comment] 2018-12-16 15:59
At line 662 in FPM.cpp, change this: 
```
if (outStream != NULL) {
      outStream->write(byte);
}
```
to
```
if (outStream != NULL) {
      outStream->write(byte);
      chksum += byte;
}
```
and this at 685:
`if (outStream == NULL && to_check != chksum) `
to:
`if (to_check != chksum)`

**Comment by brianrho** [comment] 2018-12-16 16:00
Let me know if it prints "Wrong chksum" for any packet.

**Comment by brianrho** [comment] 2018-12-16 16:02
`outStream->write(byte);` should still be commented out as before.

**Comment by baku-hatsu** [comment] 2018-12-16 16:09
It prints that for every stream packet

**Comment by brianrho** [comment] 2018-12-16 16:14
What of the PID and length? There was no wrong chksum in the earlier commands, right?

**Comment by baku-hatsu** [comment] 2018-12-16 16:15
[+]Wrong chksum
[+]PID: 0x2
[+]Length: 128

[+]Wrong chksum

Read data failed: -1

Error receiving packet 0

**Comment by brianrho** [comment] 2018-12-16 16:18
You mean, there was no "wrong chksum" before the stream began, but then after that, each packet has a wrong chksum? ALL the packets with wrong chksums have a PID of 0x2?

**Comment by baku-hatsu** [comment] 2018-12-16 16:18
Yes

**Comment by baku-hatsu** [comment] 2018-12-16 16:31
https://pastebin.com/Xcpz16Vv the serial monitor
https://pastebin.com/vZpz5D75 fpm.cpp file

**Comment by brianrho** [comment] 2018-12-16 16:55
Have you restarted the module, since you started using it to get images?

**Comment by brianrho** [comment] 2018-12-16 16:56
The packet length setting is being ignored for some reason and it could be because it hasn't taken hold yet.

**Comment by baku-hatsu** [comment] 2018-12-16 16:59
Probably not, how do i reset it? using reset pin or just unplug?

**Comment by brianrho** [comment] 2018-12-16 17:00
Just unplug from power and try again.

**Comment by baku-hatsu** [comment] 2018-12-16 17:01
There is same error

**Comment by brianrho** [comment] 2018-12-16 17:04
Okay then. Lets reset the packet length to 32 and restart. Change this line in the sketch:

`uint8_t value = FPM_PLEN_128;`

to:

`uint8_t value = FPM_PLEN_32;`

Restart the module and try the sketch again. Update the serial monitor dump at the same pastebin link.

**Comment by brianrho** [comment] 2018-12-16 17:07
Remove the header and address debug messages too

**Comment by baku-hatsu** [comment] 2018-12-16 17:15
https://pastebin.com/SRYQ6X1J new pastebin, because i cant edit old one

**Comment by brianrho** [comment] 2018-12-16 17:20
How are you powering the module?

**Comment by brianrho** [comment] 2018-12-16 17:20
The Arduino 3.3V pin?

**Comment by brianrho** [comment] 2018-12-16 17:30
Yeah try powering the sensor with the RPi 3.3V pin, no need to connect anything else to the RPi, just power it. Run the sketch again and update the dump. You can update it at the bottom

**Comment by brianrho** [comment] 2018-12-16 17:31
Sorry, you can edit it at the top of the text window. Just use Find in your browser to search for "edit"

**Comment by baku-hatsu** [comment] 2018-12-16 17:40
Apparently i have to be logged in to be able to edit so i just rather paste new ones
https://pastebin.com/5hiCpBND

**Comment by brianrho** [comment] 2018-12-16 17:45
Okay. Run it again. Seems the very first image packet has a correct checksum but the ones that follow are wrong.

**Comment by baku-hatsu** [comment] 2018-12-16 17:48
https://pastebin.com/tVU2i7zR

this is what i got now

**Comment by brianrho** [comment] 2018-12-16 17:50
Okay comment out the address, PID and length messages. Only the image bytes should be printed and "wrong chksum"

**Comment by baku-hatsu** [comment] 2018-12-16 17:57
https://pastebin.com/TxLStMxC

**Comment by brianrho** [comment] 2018-12-16 17:58
Run the "set_parameters" example. It will change the baud rate to 9600. Then run the image_to_pc again with SoftwareSerial baud rate of 9600.

**Comment by brianrho** [comment] 2018-12-16 18:00
Remember to comment out the Address debug messages.

**Comment by baku-hatsu** [comment] 2018-12-16 18:07
Apparently for some reason Arduino does not recognize fingerprint anymore

**Comment by brianrho** [comment] 2018-12-16 18:08
Did you update this line `fserial.begin(57600);` to `fserial.begin(9600);`?

**Comment by brianrho** [comment] 2018-12-16 18:08
The baud rate is now 9600 so you need to change it in your sketch

**Comment by baku-hatsu** [comment] 2018-12-16 18:09
Alright, now i get Unknow error
![image](https://user-images.githubusercontent.com/37425895/50057111-83c0ed00-016e-11e9-9ec5-335ebcea0e84.png)

**Comment by brianrho** [comment] 2018-12-16 18:11
Is this with the "image_to_pc" sketch?

**Comment by brianrho** [comment] 2018-12-16 18:11
Restart the module and run the sketch

**Comment by baku-hatsu** [comment] 2018-12-16 18:14
![image](https://user-images.githubusercontent.com/37425895/50057159-35f8b480-016f-11e9-9cfc-544324f6dbfc.png)
I get this and nothingh happen after this

**Comment by brianrho** [comment] 2018-12-16 18:15
Looks like the debug messages are disabled

**Comment by baku-hatsu** [comment] 2018-12-16 18:19
Now i get this
https://pastebin.com/JDTf2cv6

**Comment by brianrho** [comment] 2018-12-16 18:31
Disable debug. Run the sketch and wait for the image stream to complete. You wont see any bytes printed except the final error/success message.

**Comment by baku-hatsu** [comment] 2018-12-16 18:32
![image](https://user-images.githubusercontent.com/37425895/50057346-bfa98180-0171-11e9-8933-e3341ef532ba.png)

**Comment by baku-hatsu** [comment] 2018-12-16 18:33
Seems like it read all bytes 192x192

**Comment by brianrho** [comment] 2018-12-16 18:34
yes. The problem seems to have been the delays from the debug messages. Try running this with the python script now.

**Comment by baku-hatsu** [comment] 2018-12-16 18:38
![image](https://user-images.githubusercontent.com/37425895/50057399-92110800-0172-11e9-86a3-f36ad16def7c.png)

**Comment by brianrho** [comment] 2018-12-16 18:40
Oh yeah, you need to put back this line: outStream->write(byte); in FPM.cpp so the bytes actually get written

**Comment by baku-hatsu** [comment] 2018-12-16 18:40
Do i leave cheksum as well?

**Comment by brianrho** [comment] 2018-12-16 18:41
Yeah leave it as is

**Comment by baku-hatsu** [comment] 2018-12-16 18:44
![image](https://user-images.githubusercontent.com/37425895/50057450-5460af00-0173-11e9-889f-8993c43dc8c5.png)
![asdasd](https://user-images.githubusercontent.com/37425895/50057451-562a7280-0173-11e9-87d0-9fbceb558df3.png)

**Comment by brianrho** [comment] 2018-12-16 18:53
Use this script instead: https://pastebin.com/wenMKKGN. It seems the module datasheet is also wrong and every byte of the image is being sent, not half. The script expects 18432 bytes not 36864

**Comment by baku-hatsu** [comment] 2018-12-16 18:58
![asdasdasdasdasdasd](https://user-images.githubusercontent.com/37425895/50057576-33995900-0175-11e9-93f3-e5c5f2ff3893.png)
Now i can almost see image, however its somehow divided into 3 and bottom is just white

**Comment by brianrho** [comment] 2018-12-16 18:59
Let me see the console output

**Comment by baku-hatsu** [comment] 2018-12-16 19:00
![image](https://user-images.githubusercontent.com/37425895/50057614-a73b6600-0175-11e9-862d-924997b91446.png)

**Comment by brianrho** [comment] 2018-12-16 19:01
This result is the same everytime?

**Comment by baku-hatsu** [comment] 2018-12-16 19:03
Yea

**Comment by brianrho** [comment] 2018-12-16 19:17
At this point, the issue is the format of the image. I assumed its a simple grid of 192x192 like they said but if its not then it will require some analysis to detect the image dimensions. Try this: https://pastebin.com/wenMKKGN. I've set the image size to 384x192.

**Comment by brianrho** [comment] 2018-12-16 19:18
If it doesn't work, we'll have to leave it for now. You can send me the raw 192*192 image and I can check it out later. Maybe you can also search the web for the R551 SDK or contact sellers/manufacturers. Ask them about the image dimensions.

**Comment by baku-hatsu** [comment] 2018-12-16 19:20
![asdasdasdasdasdasd](https://user-images.githubusercontent.com/37425895/50057817-5bd68700-0178-11e9-88fe-6cab2de65532.png)
![sometest](https://user-images.githubusercontent.com/37425895/50057818-5c6f1d80-0178-11e9-9ed1-071a4d1b6fd7.png)
These are 192x192 and 384x192
I will try contact seller for dimentions, but i think they wont be any of help

**Comment by brianrho** [comment] 2018-12-16 19:46
Set the dimensions back to 192x192 and send the generated bmp. Will look at it later and see if theres a way to get the dimensions.
Make sure this line 117 in the script says `out.write(byte)` and line 18 says `BITMAP_SIZE = int(WIDTH * HEIGHT)`

**Comment by baku-hatsu** [comment] 2018-12-16 19:57
![testtosend](https://user-images.githubusercontent.com/37425895/50058202-968eee00-017d-11e9-8a7b-9d23dcafc713.png)

**Comment by baku-hatsu** [comment] 2018-12-16 19:58
With the default size, it seems to get better, tho it have white space at bottom n right side

**Comment by brianrho** [comment] 2018-12-16 20:16
Yeah, I noticed a lot of white (FF) in the image bytes received earlier. It could be that the image download isnt implemented properly by these guys or the correct command is missing from the datasheet. There was a similar issue before with this same module, regarding different template sizes and undocumented sleep commands. Attach the actual bmp and send that to my email, not this png.

**Comment by KobeKey** [comment] 2019-02-04 11:19
Is this still an issue ?

**Comment by brianrho** [comment] 2019-02-05 02:57
@KobeKey Yeah, we never got the image to render correctly but we also don't know what "correctly" is, for this module. So if you want, I can send the GUI demo software so you can try getting the image and I can compare your output with what we got before

**Comment by KobeKey** [comment] 2019-02-05 12:40
Well the thing is, I am a beginner in these things. I just want to make my room door open with my fingerprint, which is not hard. But after seeing all the issues with the R551 module, I think about canceling my order which was done about 2 days ago. Do you recommend me to try it out or to order a other module. Because I've seen 2 new issues opened today about the R551 module and it is worrying me.

**Comment by KobeKey** [comment] 2019-02-05 12:44
But the thing is that, the problem with image_to_pc is a problem only if I want to extract the pictures taken from the fingerprint sensor. What if I was to use it just to open an electric door lock, while having this issue ? Since I do not need the image of the fingerprint, a false image in the library will be compared to the same false image processed while putting my fingerprint, and it would be a match. So is it worth to cancel my order and take another module that is working properly ?

**Comment by baku-hatsu** [comment] 2019-02-05 18:57
If you need to compare two images from two devices, I'm afraid this library
is not gonna work yet. (I personally didn't had time to sit back on this
yet because of work, but in future i think ill work on this again) There
are given recommendations above in the discussion, so you probably should
get those ones. They are bigger, but they would work.

2019-02-05, an, 14:44 KobeKey <notifications@github.com> rašė:

**Comment by brianrho** [comment] 2019-02-05 23:00
Yes, you should probably cancel your order, the module is more trouble than its worth, I dont remember any particular benefits over others like the FPM10 for instance. Get an FPM10 or R307.
You dont need fingerprint images anyways, from what I can tell of your application. All the templates can be stored locally in the sensor (up to 1000 for those modules I mentioned) and you can use the returned finger IDs to control access to your door.

**Comment by KobeKey** [comment] 2019-02-05 23:33
Yes exactly, so even for this simple application which is the main purpose of these modules , do you recommend to cancel the order ?

**Comment by brianrho** [comment] 2019-02-05 23:36
Yes, like I said, cancel it if you still can and get an FPM10

**Comment by KobeKey** [comment] 2019-02-05 23:37
Thank you! Just ordered the FPM10a

**Comment by unangwarsodi** [comment] 2019-02-15 09:29
why does an error like this appear?
![error_get_image](https://user-images.githubusercontent.com/24889210/52847466-d9018680-313e-11e9-979b-53b41d157dac.PNG)

**Comment by brianrho** [comment] 2019-02-15 11:32
Did you upload the image_to_pc sketch?

**Comment by eduferbur** [comment] 2019-03-22 16:11
Hi! I am new here.  
I bought this device many weeks ago. After paying it I saw this topic and I got worry.
I tested it, and I came to same problem as you. 
I contacted with the buyer, and they have just sent me SDK files. 
Here you have the SDK link: https://www.dropbox.com/sh/pznvlzx8qx5nfr3/AABpzhSyjqH0qWNYgMvxqAA9a?dl=0

I will test it during these days. 
Just hope these files were helpful for who need it. 

My intention it using the R551 in a Beaglebone SBC with linux (like raspberry), take the fingerprint encripted and upload it to my server. Then I will compare the incoming fingerprint with a database using the SDK and return OK if matches or not to the beaglebone. 

I will comment here when I get some conclusion. 

If anyone has some help, I will thanks in advance! 

Nice day!

**Comment by baku-hatsu** [comment] 2019-03-22 17:02
Hello,

I still have not looked into SDK files just yet, but in upcoming month or
two ill sit down to do all kinds of things possible. If you have a choice,
you should order new scanners. Once i look into my solution i think we
would be trying reach same goal (to send fingerprint picture to the
server), so i will inform on my things once it show some positive results.

Good luck.

2019-03-22, pn, 18:11 eduferbur <notifications@github.com> rašė:

**Comment by brianrho** [comment] 2019-03-22 17:08
@eduferbur The R551 SDK doesn't provide a way to make comparisons on a regular PC, *without* the sensor. From what I've seen, you can only generate templates from images, and even for that, there is no source code, just a DLL for windows. So even with all the templates in your database, you'll still have no means to perform matching, unless you use some other algorithm with the original images instead. Still, I'm interested in finding out if the demo software works for you, and provides complete fingerprint images.

**Comment by eduferbur** [comment] 2019-03-22 17:54
@brianrho I still hadn't time to look the SDK, you are really fast hehe. I will write here my result. Thanks for the fast help. 

@baku-hatsu, thanks for you advide, I will insist many week and then will change if there is no result. Just take care cuz it is forbidden sent a fingerprint image to a server, at least in Spain. For data protection, you can only send a stronge encripted fingerprint. I still don't know much more about this topic, if you are using it for a commercial use, a hacker can give to you legal problems. 

As I say, I will send result in these days.

**Comment by baku-hatsu** [comment] 2019-03-22 20:20
Hello,

What Brian Ejike said is true, however there is SourceAFIS opensource
library where you can perform any kind of actions you desire while having
the image of the fingerprint. I offer you to look into that, Only thing you
need from scanner is the receive accurate image.

2019-03-22, pn, 19:54 eduferbur <notifications@github.com> rašė:

**Comment by saitokojiro** [comment] 2019-04-13 12:29
hello
i have a 2 problem with your program getImage.exe and getImage.py. do you know how i could solve the problem ?

![Capture](https://user-images.githubusercontent.com/31585506/56079724-6cca9880-5df8-11e9-97ee-a4e84e3d40eb.PNG)

**Comment by brianrho** [comment] 2019-04-13 15:21
Did you first upload the `image_to_pc` example to your Arduino? What's the name of your module and the name of your MCU/board? 

To run the python script, you need to install the `pyserial` package with `pip install pyserial` from the command line.

**Comment by saitokojiro** [comment] 2019-04-13 19:08
yes i first upload  the image_to_pc example. i have arduino uno rev 3

**Comment by brianrho** [comment] 2019-04-13 19:50
We've been through this on this thread before and it was never resolved. Don't change any of the script settings. Only thing you need to uncomment is `FPM_R551_MODULE` in `FPM.h`. Use everything else as is. If the image doesn't show as expected, try running the `Test Demo V2.7` in the [SDK]( https://www.dropbox.com/sh/pznvlzx8qx5nfr3/AABpzhSyjqH0qWNYgMvxqAA9a?dl=0) and using that to get an image. If you get a better image, let's see it.

**Comment by saitokojiro** [comment] 2019-04-13 19:59
I have a problem with the Demo Test V3.012
![Capture](https://user-images.githubusercontent.com/31585506/56084724-732c3500-5e37-11e9-8e09-9f5b9b60fc96.PNG)

**Comment by brianrho** [comment] 2019-04-13 20:02
You'll need to connect the sensor to the PC directly with a UART-USB adapter. Then select the right COM port in the demo app.

**Comment by saitokojiro** [comment] 2019-04-13 20:06
ok I will try

**Comment by ALTAMSH** [comment] 2019-05-25 15:56
I have the same problem, i have also tried direct with pc but it didn't solve my problem.

**Comment by ALTAMSH** [comment] 2019-05-25 16:00
![fingerprint problem](https://user-images.githubusercontent.com/49808492/58371961-150f6900-7f30-11e9-9d6d-0c3ceb333b77.PNG)

**Comment by brianrho** [comment] 2019-05-25 22:19
Create a new issue to make this easier to follow. Then provide details about the name of your sensor and how you connected it to your PC.

**Closed by brianrho** 2019-05-25 22:19 UTC
